[workspace]
resolver = "3"
members = ["crates/*", "widget"]
exclude = ["windows-rs"]

[workspace.package]
version = "0.3.0"
edition = "2024"
rust-version = "1.98.1"
authors = ["Rishabh Kumar <admin@rockerrishabh.me>"]
license = "MIT OR Apache-2.0"
description = "Real-time network bandwidth telemetry monitor and native Windows 11 widget"
repository = "https://github.com/rockerrishabh/net-flow"
homepage = "https://netflow.rockerrishabh.me"
documentation = "https://github.com/rockerrishabh/net-flow"
readme = "README.md"
keywords = ["network", "bandwidth", "windows11", "widget", "telemetry"]
categories = ["network-programming", "os::windows-apis"]


[workspace.dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

net-flow-core = { path = "crates/core" }

windows = { version = "0.62.2", features = [
    "Data_Xml_Dom",
    "UI_Notifications",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_Networking_WinSock",
    "Win32_System_Registry",
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
] }
windows-core = "0.100.0"
windows-collections = "0.100.0"
windows-reference = "0.100.0"
windows-time = "0.100.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"
