[package]
name = "net-flow"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
net-flow-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
windows-core = { workspace = true }
windows-collections = { workspace = true }
windows-reference = { workspace = true }
windows-time = { workspace = true }
windows = { workspace = true }

[build-dependencies]
windows-bindgen = "0.100.0"
winres = "0.1.12"
